### ISSUE TITLE
QueryPC2::uniprot_id_to_reactome_pathways returns more results than RTX

### ISSUE THREAD

**Issue by erikyao** [kevinxin90/RTX_BioThings_Explorer#1]
Hi Kevin, 

MWE in RTX: `pc.uniprot_id_to_reactome_pathways("P68871")`. 

- First we will get [http://www.pathwaycommons.org/pc2/search.json?q=P68871&type=pathway](http://www.pathwaycommons.org/pc2/search.json?q=P68871&type=pathway)
- Then react ID appears only in `json["searchHit"]["pathway"]` will be fetched.
- Another react ID will appear in `json["searchHit"]["uri"]` but we don't count it in. E.g. `R-HSA-6798695`

MWE in BioThings: 

- First we access [http://biothings.io/explorer/api/v2/directinput2output?input_prefix=uniprot&output_prefix=ncbigene&input_value=P68871](http://biothings.io/explorer/api/v2/directinput2output?input_prefix=uniprot&output_prefix=ncbigene&input_value=P68871) and get `ncbigene:3043`
- Then we get [http://biothings.io/explorer/api/v2/directinput2output?input_prefix=ncbigene&output_prefix=reactome.pathway&input_value=3043](http://biothings.io/explorer/api/v2/directinput2output?input_prefix=ncbigene&output_prefix=reactome.pathway&input_value=3043)
- Looks like we count all the react ID in Pathway Commons `json["searchHit"]["uri"]` in the response.

I don't know which side is correct, RTX or BioThings. Could you please check it out? Thanks!

Best,
Yao

**Comment by kevinxin90** [comment]
@erikyao 
Hi Yao, my understanding is that you should trust the results from BioThings Explorer (which contains both json['searchHit']['pathway'] and json['serachHit']['uri']). 

When you make a query like this: http://www.pathwaycommons.org/pc2/search.json?q=P68871&type=pathway. 

- The['searchHit']['uri'] represents the direct pathway which this protein 'P68871' is involved, e.g. R-HSA-6798695. 

- And the ['searchHit']['pathway'] field represents the parent pathways of 'R-HSA-6798695', e.g. R-HSA-168249, R-HSA-168256. 

I am using one part of JSON output as example here:
`{
"uri": "http://identifiers.org/reactome/R-HSA-6798695",
"biopaxClass": "Pathway",
"name": "Neutrophil degranulation",
"dataSource": [
"http://pathwaycommons.org/pc2/reactome"
],
"organism": [
"http://identifiers.org/taxonomy/9606"
],
"pathway": [
"http://identifiers.org/reactome/R-HSA-168249",
"http://identifiers.org/reactome/R-HSA-168256"
],
"excerpt": null,
"size": 1319,
"numParticipants": 1309,
"numProcesses": 10
},
You could double check the web page from reactome:http://reactome.org/content/detail/R-HSA-6798695. When you scroll down to the row 'Participant of', you should see 'Innate Immune System'. (This is the parent pathway of R-HSA-6798695). And if you click on it, it should lead you to http://reactome.org/content/detail/R-HSA-168249. And if you look for the parent for R-HSA-168249, you should find R-HSA-168256.
Given that, I think when you are querying for all pathways which a protein/gene participates in, you should both include all the results. In the current parser in RTX, you are only including the parents results, which is not sufficient.
And BTW, because the PC API is not well designed (e.g. they use URI to represent values), I chose not to include them in BioThings Explorer. So when you are querying for uniprot-reactome association, you are directly getting results from MyGene.info. And the data source of MyGene.info for pathway directly comes from Reactome, which you surely can trust.
Let me know if you have any further questions!

**Comment by erikyao** [comment]
Good. I’ll record this as a bug of RTX.

Thank you, Kevin.
